# Generated by Django 2.2.dev20181026085730 on 2018-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(default=100)),
                ('card_number', models.IntegerField(default=8)),
            ],
        ),
    ]
