# Generated by Django 2.2.dev20181026085730 on 2018-10-26 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
