# Generated by Django 2.2.dev20190116205049 on 2019-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packet', '0002_packet_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='image',
            field=models.ImageField(default='packets/static/img/no-img.jpg', upload_to='packets/static/img/'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
