version: "3"

services:

# ------> django ------>
    django_10aqh9wjmvqfjbw:
        container_name: django_10aqh9wjmvqfjbw
        build: ./django
        image: skyflow/django
        restart: always
        volumes:
            - ../:/app
        ports:
            - 8000:8000
        depends_on:
            - postgres_10aqh9wjmvqfjbx
        command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
# <------ django <------

# ------> postgres ------>
    postgres_10aqh9wjmvqfjbx:
        container_name: postgres_10aqh9wjmvqfjbx
        image: postgres:latest
        restart: always
        volumes:
            - ../../.database/my_app:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: hearthstone
#            PGDATA: ../../.database/my_app
        ports:
            - 5432:5432
# <------ postgres <------