# Generated by Django 2.2.dev20181026085730 on 2018-10-26 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 26, 11, 55, 56, 492299)),
        ),
    ]
