# Generated by Django 2.2.dev20181116103439 on 2018-11-21 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20181121_2014'),
        ('decks', '0002_auto_20181026_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 21, 20, 13, 51, 803767)),
        ),
    ]
