# Generated by Django 2.2.dev20181116103439 on 2018-11-21 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20181121_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='cards',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 21, 20, 26, 12, 702778)),
        ),
    ]
