# Generated by Django 2.2.dev20181121201207 on 2018-11-21 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20181121_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 21, 21, 17, 18, 48017)),
        ),
    ]
