# Generated by Django 2.2.dev20181121202047 on 2018-11-26 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0005_auto_20181121_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 20, 33, 41, 312619)),
        ),
    ]
