# Generated by Django 2.2.dev20190116205049 on 2019-01-16 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_auto_20181126_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='decks', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 16, 20, 54, 6, 279917)),
        ),
    ]
