# Generated by Django 2.1.1 on 2018-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ManyToManyField(to='cards.Type'),
        ),
    ]
