# Generated by Django 2.2.dev20181005083244 on 2018-10-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='assets/img/no-img.jpg', upload_to='assets/img/'),
        ),
    ]
