# Generated by Django 2.2.dev20181026085730 on 2018-10-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20181026_1155'),
        ('cards', '0004_auto_20181005_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decks.Deck'),
        ),
    ]
