# Generated by Django 2.2.dev20181116103439 on 2018-11-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='descr',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
    ]
