# Generated by Django 2.2.dev20181116103439 on 2018-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20181121_2026'),
        ('cards', '0006_auto_20181121_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ManyToManyField(related_name='cards', to='decks.Deck'),
        ),
    ]
