# Generated by Django 2.2.dev20181121201207 on 2018-11-21 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0007_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
