# Generated by Django 2.2.dev20190116205049 on 2019-01-16 20:54

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0009_auto_20181126_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owners',
        ),
        migrations.AddField(
            model_name='type',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.CreateModel(
            name='Card_quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='cards', through='cards.Card_quantity', to=settings.AUTH_USER_MODEL),
        ),
    ]
